# ============================================================================
# Script de documentation des possibilites de visualisation
# Dashboard Sante et Territoires
# ============================================================================

cat("\n=== GENERATION DOCUMENTATION DES POSSIBILITES ===\n\n")

# Chargement des packages
packages_requis <- c("tidyverse", "knitr", "rmarkdown", "DT")
for (pkg in packages_requis) {
  if (!require(pkg, character.only = TRUE, quietly = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
    library(pkg, character.only = TRUE)
  }
}

# Fonction pour generer le rapport HTML
generer_rapport_possibilites <- function(output_file) {
  
  cat("Generation du document des possibilites...\n")
  
  # Creer le contenu RMarkdown
  rmd_content <- c(
    '---',
    'title: "Dashboard Sante et Territoires - Possibilites de Visualisation"',
    'subtitle: "Guide complet des graphiques, cartes et analyses pour le defi data.gouv.fr"',
    'output:',
    '  html_document:',
    '    theme: cosmo',
    '    toc: true',
    '    toc_float: true',
    '    toc_depth: 3',
    '    number_sections: true',
    '---',
    '',
    '```{r setup, include=FALSE}',
    'knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)',
    '```',
    '',
    '<style>',
    'body { font-family: "Segoe UI", Arial, sans-serif; }',
    '.viz-card {',
    '  background-color: #f8f9fa;',
    '  border-left: 4px solid #007bff;',
    '  padding: 15px;',
    '  margin: 15px 0;',
    '  border-radius: 5px;',
    '}',
    '.priorite-haute {',
    '  border-left-color: #dc3545;',
    '}',
    '.priorite-moyenne {',
    '  border-left-color: #ffc107;',
    '}',
    '.priorite-basse {',
    '  border-left-color: #28a745;',
    '}',
    '.exemple {',
    '  background-color: #e7f3ff;',
    '  padding: 10px;',
    '  margin: 10px 0;',
    '  border-radius: 5px;',
    '}',
    '.tag {',
    '  display: inline-block;',
    '  padding: 3px 10px;',
    '  margin: 3px;',
    '  background-color: #6c757d;',
    '  color: white;',
    '  border-radius: 3px;',
    '  font-size: 0.85em;',
    '}',
    '.tag-carte { background-color: #17a2b8; }',
    '.tag-temps { background-color: #fd7e14; }',
    '.tag-comparaison { background-color: #6610f2; }',
    '.tag-distribution { background-color: #20c997; }',
    'h1 { color: #2c3e50; }',
    'h2 { color: #34495e; margin-top: 30px; }',
    'h3 { color: #5a6c7d; }',
    '</style>',
    '',
    '# Introduction',
    '',
    '## Contexte du projet',
    '',
    'Ce document presente toutes les possibilites de visualisation pour le dashboard **Sante et Territoires**, dans le cadre du defi data.gouv.fr. L objectif est de croiser des donnees de sante publique (ODISSE) avec des donnees sur les professionnels de sante (AMELI) pour analyser les inegalites territoriales.',
    '',
    '## Donnees disponibles',
    '',
    '### Donnees ODISSE (Sante Publique France)',
    '',
    '- Cancer : incidence et mortalite par departement',
    '- Grippe : passages urgences et actes SOS medecins par region',
    '- Maladies professionnelles (MCP) par region',
    '- Maladies cardiaques : hospitalisations',
    '- Mois sans tabac : inscriptions par departement et region',
    '- Pollution de l air : impact NO2 et PM2.5 sur mortalite et maladies',
    '- Sante mentale : episodes depressifs et tentatives de suicide par region',
    '',
    '### Donnees AMELI (Professionnels de sante)',
    '',
    '- Demographie medicale : ages moyens, part des femmes, part des +60 ans',
    '- Effectifs et densites medicales',
    '- Secteurs conventionnels',
    '- Patientele',
    '',
    '## Objectifs du dashboard',
    '',
    '1. **Visualiser les inegalites territoriales** en matiere de sante',
    '2. **Croiser offre et demande de soins** par territoire',
    '3. **Identifier les zones prioritaires** pour l action publique',
    '4. **Analyser les tendances temporelles** et les evolutions',
    '5. **Comparer les territoires** entre eux',
    '',
    '---',
    '',
    '# PARTIE 1 : Cartes Geographiques',
    '',
    '## Cartes chloroplethes (priorite HAUTE)',
    '',
    '<div class="viz-card priorite-haute">',
    '',
    '### Description',
    'Cartes colorees par departement ou region selon la valeur d un indicateur.',
    '',
    '### Cas d usage',
    '<span class="tag tag-carte">Carte</span> <span class="tag">Vue d ensemble</span> <span class="tag">Comparaison territoriale</span>',
    '',
    '#### 1. Densite medicale par departement',
    '- **Donnees** : `demographie-effectifs-et-les-densites_clean.csv`',
    '- **Indicateur** : Nombre de medecins pour 100 000 habitants',
    '- **Echelle** : Departementale',
    '- **Palette** : Gradient bleu (faible) vers rouge (forte)',
    '- **Interactivite** : Tooltip avec nom du departement, valeur exacte, rang',
    '',
    '#### 2. Taux de mortalite par cancer',
    '- **Donnees** : `cancer-incidence-et-mortalite-estimees-departement_clean.csv`',
    '- **Indicateur** : Taux standardise de mortalite pour 100 000 habitants',
    '- **Echelle** : Departementale',
    '- **Possibilite de filtrer** : Par type de cancer (tous, poumon, sein, colon, etc.)',
    '',
    '#### 3. Impact de la pollution de l air',
    '- **Donnees** : `pollution-de-l-air-impact-du-no2-et-des-pm2-5_mortalite_dep_clean.csv`',
    '- **Indicateur** : Nombre de deces attribuables a la pollution',
    '- **Echelle** : Departementale',
    '- **Slider temporel** : Evolution annuelle',
    '',
    '#### 4. Prevalence des troubles mentaux',
    '- **Donnees** : `sante-mentale-episodes-depressifs-caracterises-dans-les-12-derniers-mois_reg_clean.csv`',
    '- **Indicateur** : Pourcentage de la population',
    '- **Echelle** : Regionale',
    '',
    '### Outils recommandes',
    '- **Leaflet** (R) : Interactif, leger',
    '- **Plotly** (R/Python) : Animations fluides',
    '- **ggplot2 + sf** (R) : Cartes statiques de qualite',
    '',
    '</div>',
    '',
    '## Cartes de points (priorite MOYENNE)',
    '',
    '<div class="viz-card priorite-moyenne">',
    '',
    '### Description',
    'Localisation precise des etablissements ou evenements de sante.',
    '',
    '### Cas d usage',
    '',
    '#### 1. Carte des hopitaux par capacite',
    '- **Donnees** : `maladies-cardiaques-hospitalisations_clean.csv`',
    '- **Visualisation** : Points proportionnels au nombre d hospitalisations',
    '- **Filtre** : Par pathologie',
    '',
    '#### 2. Passes aux urgences pour grippe',
    '- **Donnees** : `grippe-passages-urgences-et-actes-sos-medecin_reg_clean.csv`',
    '- **Animation** : Evolution hebdomadaire',
    '',
    '</div>',
    '',
    '## Cartes de chaleur (heatmaps geographiques)',
    '',
    '<div class="viz-card priorite-moyenne">',
    '',
    '### Description',
    'Densite spatiale d un phenomene.',
    '',
    '### Cas d usage',
    '- **Concentration des professionnels de sante** dans les zones urbaines vs rurales',
    '- **Zones a forte prevalence** de maladies professionnelles',
    '',
    '</div>',
    '',
    '---',
    '',
    '# PARTIE 2 : Graphiques Temporels',
    '',
    '## Series temporelles (priorite HAUTE)',
    '',
    '<div class="viz-card priorite-haute">',
    '',
    '### Description',
    'Evolution d un indicateur dans le temps.',
    '',
    '### Cas d usage',
    '<span class="tag tag-temps">Temporel</span> <span class="tag">Tendance</span>',
    '',
    '#### 1. Evolution de l incidence du cancer',
    '- **Graphique** : Ligne avec points',
    '- **Donnees** : Cancer par annee',
    '- **Comparaison** : Multi-departements selectionnes',
    '- **Bandes de confiance** : Afficher l intervalle',
    '',
    '#### 2. Activite grippale hebdomadaire',
    '- **Graphique** : Ligne avec zone ombrée',
    '- **Donnees** : Passages urgences + SOS medecins',
    '- **Comparaison** : Plusieurs saisons sur un meme graphique',
    '- **Seuil d alerte** : Ligne horizontale',
    '',
    '#### 3. Evolution de la densite medicale',
    '- **Graphique** : Lignes multiples par specialite',
    '- **Donnees** : Effectifs medicaux annuels',
    '- **Projection** : Tendance future en pointilles',
    '',
    '### Outils recommandes',
    '- **Plotly** : Zoom, pan, selection',
    '- **Dygraphs** (R) : Excellente performance',
    '- **Highcharts** : Tres professionnel',
    '',
    '</div>',
    '',
    '## Graphiques en aires empilees',
    '',
    '<div class="viz-card priorite-moyenne">',
    '',
    '### Cas d usage',
    '- **Repartition par age** des medecins dans le temps',
    '- **Composition des causes de mortalite** par cancer',
    '',
    '</div>',
    '',
    '---',
    '',
    '# PARTIE 3 : Comparaisons et Distributions',
    '',
    '## Graphiques en barres (priorite HAUTE)',
    '',
    '<div class="viz-card priorite-haute">',
    '',
    '### Description',
    'Comparaison de valeurs entre categories.',
    '',
    '### Cas d usage',
    '<span class="tag tag-comparaison">Comparaison</span>',
    '',
    '#### 1. Top 10 des departements',
    '- **Par densite medicale** (croissant/decroissant)',
    '- **Par taux de mortalite** par cancer',
    '- **Par taux d hospitalisation** cardiaque',
    '',
    '#### 2. Comparaison avant/apres',
    '- **Inscriptions Mois Sans Tabac** : evolution annuelle',
    '- **Graphique** : Barres groupees',
    '',
    '#### 3. Repartition par sexe',
    '- **Part des femmes** dans les professions medicales',
    '- **Graphique** : Barres horizontales',
    '',
    '</div>',
    '',
    '## Boites a moustaches (box plots)',
    '',
    '<div class="viz-card priorite-moyenne">',
    '',
    '### Cas d usage',
    '<span class="tag tag-distribution">Distribution</span>',
    '',
    '- **Distribution des densites medicales** par region',
    '- **Ages moyens des medecins** par specialite',
    '- **Identifier les valeurs aberrantes** (outliers)',
    '',
    '</div>',
    '',
    '## Graphiques en violon',
    '',
    '<div class="viz-card priorite-basse">',
    '',
    '### Cas d usage',
    '- **Distribution detaillee** de la patientele par medecin',
    '- **Comparaison multi-groupes** (regions, departements)',
    '',
    '</div>',
    '',
    '---',
    '',
    '# PARTIE 4 : Correlations et Relations',
    '',
    '## Nuages de points (scatter plots) - priorite HAUTE',
    '',
    '<div class="viz-card priorite-haute">',
    '',
    '### Description',
    'Relation entre deux variables quantitatives.',
    '',
    '### Cas d usage',
    '<span class="tag">Correlation</span> <span class="tag">Relation</span>',
    '',
    '#### 1. Densite medicale vs Mortalite',
    '- **Axe X** : Densite de medecins pour 100 000 habitants',
    '- **Axe Y** : Taux de mortalite standardise',
    '- **Points** : Departements',
    '- **Taille** : Population',
    '- **Couleur** : Region',
    '- **Droite de regression** : Afficher la tendance',
    '',
    '#### 2. Pollution vs Sante respiratoire',
    '- **Axe X** : Concentration NO2 ou PM2.5',
    '- **Axe Y** : Taux d hospitalisations respiratoires',
    '- **Animation** : Evolution temporelle',
    '',
    '#### 3. Age des medecins vs Densite',
    '- **Hypothese** : Les zones a faible densite ont des medecins plus ages',
    '- **Visualisation** : Nuage avec zones de densite',
    '',
    '</div>',
    '',
    '## Matrices de correlation',
    '',
    '<div class="viz-card priorite-moyenne">',
    '',
    '### Cas d usage',
    '- **Vue d ensemble** des relations entre tous les indicateurs',
    '- **Heatmap** avec coefficients de correlation',
    '- **Hierarchical clustering** pour regrouper indicateurs similaires',
    '',
    '</div>',
    '',
    '---',
    '',
    '# PARTIE 5 : Graphiques de Composition',
    '',
    '## Graphiques circulaires (pie charts)',
    '',
    '<div class="viz-card priorite-basse">',
    '',
    '### Cas d usage (utiliser avec moderation)',
    '- **Repartition des secteurs conventionnels**',
    '- **Maximum 5-6 categories**',
    '- **Alternative preferee** : Barres horizontales',
    '',
    '</div>',
    '',
    '## Treemaps',
    '',
    '<div class="viz-card priorite-moyenne">',
    '',
    '### Cas d usage',
    '- **Repartition hierarchique** des effectifs medicaux',
    '  - Niveau 1 : Region',
    '  - Niveau 2 : Departement',
    '  - Niveau 3 : Specialite',
    '- **Taille** : Nombre de medecins',
    '- **Couleur** : Variation par rapport a la moyenne',
    '',
    '</div>',
    '',
    '## Sunburst charts',
    '',
    '<div class="viz-card priorite-basse">',
    '',
    '### Cas d usage',
    '- **Alternative au treemap** plus esthetique',
    '- **Hierarchie radiale** des donnees',
    '',
    '</div>',
    '',
    '---',
    '',
    '# PARTIE 6 : Tableaux de bord et KPIs',
    '',
    '## Indicateurs cles (KPI cards) - priorite HAUTE',
    '',
    '<div class="viz-card priorite-haute">',
    '',
    '### Description',
    'Chiffres cles en haut du dashboard.',
    '',
    '### Indicateurs essentiels',
    '',
    '1. **Nombre total de medecins en France**',
    '   - Evolution par rapport a l annee precedente (fleche)',
    '   ',
    '2. **Densite medicale moyenne nationale**',
    '   - Medecins pour 100 000 habitants',
    '   ',
    '3. **Departements sous-denses**',
    '   - Nombre et pourcentage sous le seuil',
    '   ',
    '4. **Nombre de deces attribuables a la pollution**',
    '   - Total annuel',
    '   ',
    '5. **Prevalence des troubles mentaux**',
    '   - Pourcentage national',
    '',
    '</div>',
    '',
    '## Jauges (gauges)',
    '',
    '<div class="viz-card priorite-moyenne">',
    '',
    '### Cas d usage',
    '- **Performance par rapport a un objectif**',
    '- **Exemple** : Objectif de densite medicale atteint a X%',
    '- **Zones** : Rouge (critique), Orange (attention), Vert (bon)',
    '',
    '</div>',
    '',
    '---',
    '',
    '# PARTIE 7 : Visualisations Avancees',
    '',
    '## Cartes proportionnelles (cartogrammes)',
    '',
    '<div class="viz-card priorite-basse">',
    '',
    '### Description',
    'Deformation des departements selon une variable.',
    '',
    '### Cas d usage',
    '- **Taille proportionnelle a la population**',
    '- **Couleur** : Indicateur de sante',
    '- **Utile pour corriger** la surrepresentation des zones peu peuplees',
    '',
    '</div>',
    '',
    '## Graphiques de Sankey',
    '',
    '<div class="viz-card priorite-moyenne">',
    '',
    '### Cas d usage',
    '- **Flux de patients** entre territoires',
    '- **Mobilite des professionnels de sante**',
    '- **Parcours de soins**',
    '',
    '</div>',
    '',
    '## Radar charts (graphiques en toile d araignee)',
    '',
    '<div class="viz-card priorite-moyenne">',
    '',
    '### Cas d usage',
    '- **Profil multi-dimensionnel d un territoire**',
    '  - Densite medicale',
    '  - Taux de mortalite',
    '  - Pollution',
    '  - Sante mentale',
    '  - Etc.',
    '- **Comparaison de 2-3 territoires**',
    '',
    '</div>',
    '',
    '## Graphiques de pente (slope charts)',
    '',
    '<div class="viz-card priorite-moyenne">',
    '',
    '### Cas d usage',
    '- **Evolution entre deux annees** pour plusieurs entites',
    '- **Exemple** : Classement des regions avant/apres',
    '- **Excellente lisibilite** pour les changements de rang',
    '',
    '</div>',
    '',
    '---',
    '',
    '# PARTIE 8 : Analyses Croisees (PRIORITE MAXIMALE)',
    '',
    '## Vue combinee Offre-Demande',
    '',
    '<div class="viz-card priorite-haute">',
    '',
    '### Description',
    'LE graphique cle du dashboard : croiser donnees ODISSE (besoins) et AMELI (offre).',
    '',
    '### Visualisation 1 : Matrice 2x2',
    '',
    '**Axes** :',
    '- **Axe X** : Densite medicale (faible a forte)',
    '- **Axe Y** : Besoins de sante (faible a fort)',
    '',
    '**Quadrants** :',
    '- **Haut-Gauche** (ROUGE) : Besoins forts + Densite faible = PRIORITE MAX',
    '- **Haut-Droit** (ORANGE) : Besoins forts + Densite forte = Surveillance',
    '- **Bas-Gauche** (JAUNE) : Besoins faibles + Densite faible = A surveiller',
    '- **Bas-Droit** (VERT) : Besoins faibles + Densite forte = Situation favorable',
    '',
    '**Points** : Departements',
    '**Taille** : Population',
    '**Interactivite** : Clic pour detail',
    '',
    '### Visualisation 2 : Carte bichromatique',
    '',
    '- **Premiere couche** (fond) : Mortalite (gradient rouge)',
    '- **Deuxieme couche** (points) : Densite medicale (taille des cercles)',
    '- **Objectif** : Voir visuellement les decalages',
    '',
    '### Visualisation 3 : Graphique en barres divergentes',
    '',
    '- **Chaque departement** : une barre',
    '- **A gauche** : Deficit d offre (rouge)',
    '- **A droite** : Surplus d offre (vert)',
    '- **Calcul** : (Offre observee - Offre attendue selon besoins) / Offre attendue',
    '',
    '</div>',
    '',
    '## Analyses multi-criteres',
    '',
    '<div class="viz-card priorite-haute">',
    '',
    '### Score synthetique de fragilite territoriale',
    '',
    '**Composantes** :',
    '1. Densite medicale (25%)',
    '2. Mortalite evitable (25%)',
    '3. Impact pollution (20%)',
    '4. Sante mentale (15%)',
    '5. Age des medecins (15%)',
    '',
    '**Visualisation** :',
    '- **Carte choroplthe** du score',
    '- **Classement** des 20 territoires les plus fragiles',
    '- **Detail** : Radar chart pour chaque territoire',
    '',
    '</div>',
    '',
    '---',
    '',
    '# PARTIE 9 : Interactivite et Filtres',
    '',
    '## Filtres indispensables',
    '',
    '<div class="viz-card priorite-haute">',
    '',
    '### Filtres geographiques',
    '- **Selection de regions** (multi-select)',
    '- **Selection de departements**',
    '- **Rural vs Urbain**',
    '',
    '### Filtres temporels',
    '- **Slider annees** (de 2015 a 2023)',
    '- **Selection periode** (avant/apres COVID)',
    '',
    '### Filtres thematiques',
    '- **Type de pathologie** (cancer, cardio, respiratoire)',
    '- **Type de professionnel** (medecins generalistes, specialistes)',
    '- **Tranche d age** des professionnels',
    '',
    '</div>',
    '',
    '## Elements interactifs',
    '',
    '<div class="viz-card priorite-moyenne">',
    '',
    '### Tooltips (info-bulles)',
    'Afficher au survol :',
    '- Nom du territoire',
    '- Valeur exacte',
    '- Rang',
    '- Evolution',
    '',
    '### Click-through',
    '- **Clic sur departement** : Ouvre fiche detaillee',
    '- **Clic sur point** : Affiche serie temporelle',
    '',
    '### Zoom et pan',
    '- Sur les cartes',
    '- Sur les series temporelles',
    '',
    '</div>',
    '',
    '---',
    '',
    '# PARTIE 10 : Architecture du Dashboard',
    '',
    '## Structure recommandee',
    '',
    '### Page 1 : Vue d ensemble nationale',
    '1. **En-tete** : KPIs principaux',
    '2. **Carte nationale** : Densite medicale',
    '3. **Graphique** : Evolution temporelle nationale',
    '4. **Top 10** : Departements sous-denses',
    '',
    '### Page 2 : Sante publique (ODISSE)',
    '1. **Onglets par theme** :',
    '   - Cancer',
    '   - Maladies cardiaques',
    '   - Sante mentale',
    '   - Pollution',
    '   - Grippe',
    '2. **Pour chaque theme** :',
    '   - Carte',
    '   - Serie temporelle',
    '   - Comparaisons',
    '',
    '### Page 3 : Professionnels de sante (AMELI)',
    '1. **Demographie** :',
    '   - Pyramide des ages',
    '   - Repartition par sexe',
    '   - Projection futures',
    '2. **Densite** :',
    '   - Carte',
    '   - Evolution',
    '   - Comparaisons internationales',
    '',
    '### Page 4 : Analyses croisees (COEUR DU DASHBOARD)',
    '1. **Matrice Offre-Demande** (graphique principal)',
    '2. **Score de fragilite territoriale**',
    '3. **Analyses de correlation**',
    '4. **Fiches detaillees** par departement',
    '',
    '### Page 5 : A propos et methodo',
    '1. **Sources des donnees**',
    '2. **Methodologie**',
    '3. **Definitions**',
    '4. **Contact**',
    '',
    '## Outils techniques recommandes',
    '',
    '### Option 1 : Shiny (R) - RECOMMANDE',
    '**Avantages** :',
    '- Integration parfaite avec R',
    '- Plotly + Leaflet + DT',
    '- Facile a deployer',
    '',
    '**Packages cles** :',
    '- `shiny` : Framework',
    '- `shinydashboard` : Structure',
    '- `plotly` : Graphiques interactifs',
    '- `leaflet` : Cartes',
    '- `DT` : Tableaux',
    '- `sf` : Donnees geographiques',
    '',
    '### Option 2 : Dash (Python)',
    '**Avantages** :',
    '- Tres performant',
    '- Plotly natif',
    '- Bonne documentation',
    '',
    '### Option 3 : Observable (JavaScript)',
    '**Avantages** :',
    '- Tres fluide',
    '- D3.js pour visualisations custom',
    '- Partage facile',
    '',
    '---',
    '',
    '# PARTIE 11 : Priorites de developpement',
    '',
    '## Phase 1 : MVP (Minimum Viable Product)',
    '',
    '### Semaine 1-2',
    '1. Page d accueil avec KPIs',
    '2. Carte de densite medicale',
    '3. Tableau de classement des departements',
    '',
    '### Semaine 3-4',
    '4. Graphiques temporels principaux',
    '5. Filtres geographiques',
    '6. Page Sante publique (theme Cancer)',
    '',
    '## Phase 2 : Dashboard complet',
    '',
    '### Semaine 5-6',
    '7. Tous les themes ODISSE',
    '8. Page Professionnels de sante',
    '9. Analyses croisees basiques',
    '',
    '### Semaine 7-8',
    '10. Matrice Offre-Demande avancee',
    '11. Score de fragilite territoriale',
    '12. Fiches departementales',
    '',
    '## Phase 3 : Ameliorations',
    '',
    '### Semaine 9-10',
    '13. Animations',
    '14. Graphiques avances',
    '15. Export PDF/PNG',
    '16. Responsive design',
    '',
    '---',
    '',
    '# PARTIE 12 : Checklist Finale',
    '',
    '## Visualisations essentielles (a avoir absolument)',
    '',
    '- [ ] Carte de densite medicale par departement',
    '- [ ] Serie temporelle evolution densite',
    '- [ ] Top 10 departements sous-denses',
    '- [ ] Carte de mortalite par cancer',
    '- [ ] Nuage de points Densite vs Mortalite',
    '- [ ] Matrice 2x2 Offre-Demande',
    '- [ ] Score de fragilite territoriale',
    '- [ ] KPIs principaux',
    '',
    '## Fonctionnalites essentielles',
    '',
    '- [ ] Filtres geographiques',
    '- [ ] Slider temporel',
    '- [ ] Tooltips informatifs',
    '- [ ] Click-through vers details',
    '- [ ] Export des donnees',
    '- [ ] Version mobile',
    '',
    '## Qualite',
    '',
    '- [ ] Temps de chargement < 3 secondes',
    '- [ ] Legende claire sur chaque graphique',
    '- [ ] Sources citees',
    '- [ ] Accessibilite (contraste, textes alternatifs)',
    '- [ ] Tests sur plusieurs navigateurs',
    '',
    '---',
    '',
    '# Conclusion',
    '',
    'Ce document repertorie **plus de 30 types de visualisations** adaptees au dashboard Sante et Territoires. Les visualisations marquees comme **priorite HAUTE** doivent etre developpees en premier pour repondre aux objectifs du defi.',
    '',
    '## Principe KISS (Keep It Simple, Stupid)',
    '',
    'Mieux vaut avoir **5 visualisations excellentes** que 20 visualisations moyennes. Focalisez-vous sur :',
    '',
    '1. La **clarte** : Un graphique doit se comprendre en 5 secondes',
    '2. L **utilite** : Chaque visualisation doit repondre a une question',
    '3. L **interactivite** : L utilisateur doit pouvoir explorer',
    '4. La **coherence** : Style visuel uniforme',
    '',
    '## Contact et ressources',
    '',
    '- **Documentation R Shiny** : https://shiny.posit.co/',
    '- **Galerie Plotly** : https://plotly.com/r/',
    '- **Exemples Leaflet** : https://rstudio.github.io/leaflet/',
    '- **Inspiration** : https://www.r-graph-gallery.com/',
    '',
    '---',
    '',
    '*Document genere automatiquement le* `r format(Sys.time(), "%d %B %Y")`'
  )
  
  # Sauvegarder le fichier RMarkdown
  temp_rmd <- tempfile(fileext = ".Rmd")
  writeLines(rmd_content, temp_rmd, useBytes = TRUE)
  
  # Generer le HTML
  tryCatch({
    rmarkdown::render(temp_rmd, output_file = output_file, quiet = FALSE)
    cat("\nRapport genere avec succes!\n")
    cat("Fichier:", output_file, "\n")
  }, error = function(e) {
    cat("\nErreur lors de la generation:", e$message, "\n")
    stop("Echec generation")
  })
  
  # Nettoyer
  unlink(temp_rmd)
}

# ============================================================================
# EXECUTION
# ============================================================================

cat("\n=== DASHBOARD SANTE ET TERRITOIRES ===\n")
cat("Generation de la documentation des possibilites\n\n")

# Definir le chemin de sortie
chemin_base <- "D:/MASTER MECEN/MASTER 1/opendata"
fichier_sortie <- file.path(chemin_base, "data/processed/possibilites_visualisation.html")

# Creer le dossier si necessaire
dir.create(dirname(fichier_sortie), recursive = TRUE, showWarnings = FALSE)

# Generer le rapport
generer_rapport_possibilites(fichier_sortie)

cat("\n=== TERMINE ===\n")
cat("\nConsultez le document a :\n")
cat(fichier_sortie, "\n\n")
cat("Ce document contient :\n")
cat("- 30+ types de visualisations\n")
cat("- Cas d usage specifiques pour vos donnees\n")
cat("- Recommandations d outils\n")
cat("- Architecture du dashboard\n")
cat("- Plan de developpement par phases\n")
cat("- Checklist finale\n\n")
